---
title: "Datos ordinales - cuellos de las jirafas"
author: "Curso de Estadística Descriptiva"
date: "9/11/2019"
output: html_document
---

## Datos ordinales: cuellos de las jirafas

```{r}
longitud = ordered(
  c("Corto", "Normal", "Muy.corto", "Muy.corto", "Normal", "Corto", "Largo", "Muy.corto", "Muy.largo", "Normal", "Corto", "Largo", "Muy.largo", "Largo", "Muy.largo", "Largo", "Corto", "Normal", "Largo", "Muy.largo", "Corto", "Normal", "Muy.corto", "Muy.corto", "Largo", "Normal", "Corto", "Muy.largo", "Normal", "Muy.corto", "Muy.corto", "Muy.largo", "Muy.corto", "Normal", "Normal", "Largo", "Muy.corto", "Muy.corto", "Normal", "Muy.corto", "Muy.largo", "Largo", "Normal", "Normal", "Largo", "Muy.corto", "Muy.largo", "Muy.corto", "Muy.corto", "Largo", "Normal", "Corto", "Muy.corto", "Largo", "Largo", "Muy.largo", "Corto", "Largo", "Corto", "Normal", "Normal", "Corto", "Muy.largo", "Muy.corto", "Corto", "Muy.corto", "Largo", "Largo", "Muy.corto", "Normal", "Corto", "Corto", "Muy.largo", "Muy.corto", "Muy.corto", "Normal", "Largo", "Corto", "Normal", "Muy.corto", "Corto", "Largo", "Muy.corto", "Corto", "Muy.corto", "Muy.largo", "Muy.largo", "Muy.corto", "Normal", "Corto", "Muy.largo", "Muy.corto", "Corto", "Muy.largo", "Corto", "Largo", "Corto", "Corto", "Muy.largo", "Muy.largo"), 
  levels = c("Muy.corto", "Corto", "Normal", "Largo", "Muy.largo")
)
```

### Frecuencias absolutas

```{r}
Fr.Abs = table(longitud)
Fr.Abs
barplot(Fr.Abs, main = "Diagrama de barras de frecuencias absolutas")
```

### Frecuencias relativas

```{r}
Fr.Rel = prop.table(Fr.Abs)
Fr.Rel
barplot(Fr.Rel, main = "Diagrama de barras de frecuencias relativas")
```

### Frecuencias absolutas acumuladas

```{r}
Fr.Acum = cumsum(Fr.Abs)
Fr.Acum
barplot(Fr.Acum, main = "Diagrama de barras de frecuencias absolutas acumuladas")
```

### Frecuencias relativas acumuladas

```{r}
Fr.RAcum = cumsum(Fr.Rel)
Fr.RAcum
barplot(Fr.RAcum, main = "Diagrama de barras de frecuencias relativas acumuladas")
```

## Análisis de datos ordinales por factor

```{r}
zonas = rep(c("A","B","C","D"), c(30,25,35,10))
jirafas = data.frame(zonas,longitud)
str(jirafas)
head(jirafas)
table(jirafas)
```

### Longitudes por zonas (por filas)

```{r}
apply(table(jirafas), MARGIN = 1, FUN = cumsum)
t(apply(table(jirafas), MARGIN = 1, FUN = cumsum))
```

#### Diagrama

```{r}
Diagrama = apply(prop.table(table(jirafas), margin = 1), MARGIN = 1, FUN = cumsum)
barplot(Diagrama, beside = TRUE, legend = TRUE, main = "Diagrama de barras de 
        frecuencias relativas acumuladas de longitudes por zonas",
args.legend=list(x="topleft", cex=0.55))

Diagrama = t(prop.table(table(jirafas), margin = 1))
barplot(Diagrama, beside = TRUE, legend = TRUE, main = "Diagrama de barras de 
        frecuencias relativas de longitudes por zonas",
args.legend=list(x="topleft", cex=0.55))
```



