---
title: "Sección 11"
author: "Curso de Estadística Descriptiva"
date: "9/13/2019"
output: html_document
---

## Estudio de las frecuencias

### Ejemplo 1
```{r}
edad = c(15,18,25,40,30,29,56,40,13,27,42,23,11,26,25,32,30,40,33,29)
table(edad) # Frecuencias absolutas
round(prop.table(table(edad)), 3) # Frecuencias relativas
cumsum(table(edad)) # Frecuencias acumuladas absolutas
round(cumsum(prop.table(table(edad))), 3) # Frecuencias acumuladas relativas
```

### Ejemplo 2

```{r}
set.seed(162017)
dados = sample(1:6,25,replace = TRUE)
dados
set.seed(NULL)

table(dados) # Frecuencias absolutas
round(prop.table(table(dados)), 3) # Frecuencias relativas
cumsum(table(dados)) # Frecuencias acumuladas absolutas
round(cumsum(prop.table(table(dados))), 3) # Frecuencias acumuladas relativas

# as.vector para que solo introduzca los valores y sin los nombres de los niveles
dados.df = data.frame(Puntuacion = 1:6,
                      Fr.abs = as.vector(table(dados)), 
                      Fr.rel = as.vector(round(prop.table(table(dados)),2)),
                      Fr.acu = as.vector(cumsum(table(dados))),
                      Fr.racu = as.vector(round(cumsum(prop.table(table(dados))), 3))
                      )
dados.df
```

## Medidas de tendencias central

### Media aritmética
```{r}
mean(edad)
mean(dados)
```

### Mediana
```{r}
median(edad)
median(dados)
```

### Moda
```{r}
as.numeric(names(which(table(edad)==max(table(edad)))))
as.numeric(names(which(table(dados)==max(table(dados)))))
```

### Ejemplo 3
```{r}
set.seed(260798)
dado = sample(1:4, 50, replace = TRUE)
set.seed(NULL)
length(dado)

dado = sort(dado)
dado

df.dado = data.frame(Puntuacion = 1:4,
                      Fr.abs = as.vector(table(dado)),
                      Fr.rel = as.vector(round(prop.table(table(dado)),2)),
                      Fr.acu = as.vector(cumsum(table(dado))),
                      Fr.racu = as.vector(round(cumsum(prop.table(table(dado))),2)))
df.dado
```
#### Mirando la tabla anterior se puede obtener el cuantil de orden 0,3.

$$Q_{0.3} = 1$$

#### El '1' es el primer elemento de la lista cuya frecuencia relativa acumulada es mayor o igual a 0,3.

#### Otra forma de obtener el cuantil de orden 0,3:
```{r}
Q0.3 = length(dado)*0.3
Q0.3
dado[Q0.3]
```

#### Función en R para calcular cuantiles:
```{r}
quantile(dado, 0.25)
quantile(dado, 0.5)
quantile(dado, 0.75)
quantile(dado, 0.8)
```



