---
title: "Tipos de gráficos"
author: "Curso de Estadística Descriptiva"
date: "8/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tipos de gráficos

```{r tipos}
par(mfrow = c(3,2))
x = c(50:59)
y = c(2,9,25,3,100,77,62,54,19,40)
plot(x,y, type = "p")
plot(x,y, type = "l")
plot(x,y, type = "b")
plot(x,y, type = "o")
plot(x,y, type = "h")
plot(x,y, type = "s")
par(mfrow = c(1,1))
```

# Más parámetros

```{r otros_parametros}
x = (2*(1:20))
y = (-1)^(1:20)*5*(1:20)
plot(x,y, main="Ejempplo de gráfico", pch = 8, cex = 1, type = "b", lty=4, lwd="dashed", xaxp=c(0,40,10), yaxp=c(-100,100,10), xlim = c(1,10), ylim=c(-20,20))
```
```{r add_elements}
f <- function(x){
  x^2 -2*x + sqrt(abs(x))
}
plot(f, xlim = c(0,10), ylim = c(0,10), lwd=2)
points(0,0, pch = 19)
points(-3:3, (-3:3)^2, col = "blue")
abline(0,1, lty = "dashed", col = "red")
abline(v = 2, lty = "dotted", col = "green")
abline(h = 5, lty = "dotdash", col = "gray")
legend("bottomright",
				col=c("black","blue","red"), 
				lty=c("solid", "dotted", "dashed"),
				legend=c(expression(f(x)),expression(x^2), expression(x = x)),
			    lwd=2,
			    bty="n"
			    )
```

```{r}
f <- function(x){x^2}
plot(f, xlim=c(-3,3), col="red", lwd=2, ylab=expression(y^2), xlab="x")
abline(h=0:9, v=-3:3, lty ="dotted", col="grey")
```

```{r}
plot(tan, xlim = c(-pi, pi), ylim = c(-5,5))
abline(v = c(-pi/2, pi/2), col = "red")
```

```{r}
plot(0,0)
text(0,0, labels = "debajo", pos = 1)
text(0,0, labels = "izquierda", pos = 2)
text(0,0, labels = "arriba", pos = 3)
text(0,0, labels = "derecha", pos = 4)
points(0,1)
text(0,1, labels = "centro")
```

```{r}
f <- function(x){x^2}
plot(f, xlim = c(-3,3), ylim = c(-10,10))
points(-3:3, f(-3:3), pch = 19)
lines(-3:3, f(-3:3), lwd = 2, lty = "dotted", col = "red")
curve(x^3, lty = "dashed", col = "blue", add = TRUE)
curve(x^4, lty = "dashed", col = "orangered", add=TRUE)
legend("bottomright", 
	legend = c(expression(x^2), expression(x^3), expression(x^4)), 
	lwd =2, 
	col = c("red", "blue", "orangered"),
	lty = c("dotted", "dashed", "dashed")
)
```

```{r}
			x = seq(0,2*pi,0.1)
			plot(x,sin(x),type="l",col="blue",lwd=3, xlab="", ylab="")
			lines(x,cos(x),col="green",lwd=3)
			lines(x, tan(x), col="purple",lwd=3)
			legend("bottomleft",
				col=c("blue","green","purple"), 
				legend=c("Seno","Coseno", "Tangente"), 
			    lwd=3, 
			    bty="o"
			    )
```


